packages:
  - 'packages/common'
  - 'packages/grants-stack-data-client'
  - 'packages/eslint-config-gitcoin'
  - 'packages/round-manager'
  - 'packages/grant-explorer'
  - 'packages/builder'
  - 'packages/verify-env'
