packages:
  - 'packages/api'
  - 'packages/common'
  - 'packages/eslint-config-gitcoin'
  - 'packages/round-manager'
  - 'packages/grant-explorer'
  - 'packages/contracts'
  - 'packages/graph'
  - 'packages/project-registry'
