packages:
  - 'packages/common'
  - 'packages/data-layer'
  - 'packages/eslint-config-gitcoin'
  - 'packages/round-manager'
  - 'packages/grant-explorer'
  - 'packages/builder'
  - 'packages/verify-env'
