version: '3'

services:
  postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 3s
      retries: 5

  # Ephemeral db migration step
  migration:
    image: node:18-slim
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run prisma:migrate

  # Start the server
  web:
    image: node:18-slim
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - migration
    command: npm run dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    links:
      - postgres
