version: "3.8"

services:
  # Load the postgres db
  postgres:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  # Start the server
  web:
    image: boudra/pnpm-node16:latest
    build:
      context: ./
      target: dev
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    links:
      - postgres
    volumes:
      - ./src:/src
      - ./prisma:/prisma
    command: sh -c "pnpm prisma:migrate && pnpm dev"

volumes:
  postgres: {}
