version: '3.8'

services:

  # Load the postgres db
  postgres:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 3s
      timeout: 3s
      retries: 5

  # Start the server
  web:
    image: node:18-slim
    build:
      context: ./
      target: dev
      dockerfile: Dockerfile
    command: sh -c "npm run prisma:migrate && npm run dev"
    ports:
      - "8000:8000"
    env_file: 
      - .env
    links:
      - postgres 

volumes:
  postgres: {}
