/** GrantRoundImplementation contract ABI in Human Readable ABI Format  */

const roundImplementation = [
  "event ApplicationMetaPtrUpdated(tuple(uint256,string),tuple(uint256,string))",
  "event ApplicationsStartTimeUpdated(uint256,uint256)",
  "event Initialized(uint8)",
  "event NewProjectApplication(address indexed,tuple(uint256,string))",
  "event ProjectsMetaPtrUpdated(tuple(uint256,string),tuple(uint256,string))",
  "event RoleAdminChanged(bytes32 indexed,bytes32 indexed,bytes32 indexed)",
  "event RoleGranted(bytes32 indexed,address indexed,address indexed)",
  "event RoleRevoked(bytes32 indexed,address indexed,address indexed)",
  "event RoundEndTimeUpdated(uint256,uint256)",
  "event RoundMetaPtrUpdated(tuple(uint256,string),tuple(uint256,string))",
  "event RoundStartTimeUpdated(uint256,uint256)",
  "function DEFAULT_ADMIN_ROLE() view returns (bytes32)",
  "function ROUND_OPERATOR_ROLE() view returns (bytes32)",
  "function applicationMetaPtr() view returns (uint256, string)",
  "function applicationsStartTime() view returns (uint256)",
  "function applyToRound(address,tuple(uint256,string))",
  "function getRoleAdmin(bytes32) view returns (bytes32)",
  "function getRoleMember(bytes32,uint256) view returns (address)",
  "function getRoleMemberCount(bytes32) view returns (uint256)",
  "function grantRole(bytes32,address)",
  "function hasRole(bytes32,address) view returns (bool)",
  "function initialize(address,uint256,uint256,uint256,address,tuple(uint256,string),tuple(uint256,string),address,address[])",
  "function projectsMetaPtr() view returns (uint256, string)",
  "function renounceRole(bytes32,address)",
  "function revokeRole(bytes32,address)",
  "function roundEndTime() view returns (uint256)",
  "function roundMetaPtr() view returns (uint256, string)",
  "function roundStartTime() view returns (uint256)",
  "function supportsInterface(bytes4) view returns (bool)",
  "function token() view returns (address)",
  "function updateApplicationMetaPtr(tuple(uint256,string))",
  "function updateApplicationsStartTime(uint256)",
  "function updateProjectsMetaPtr(tuple(uint256,string))",
  "function updateRoundEndTime(uint256)",
  "function updateRoundMetaPtr(tuple(uint256,string))",
  "function updateRoundStartTime(uint256)",
  "function vote(bytes[])",
  "function votingStrategy() view returns (address)"
]

export default roundImplementation