name: Builder - Lint & Test & Typecheck

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - "**"

jobs:
  lint-test-typecheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - uses: pnpm/action-setup@v4
      with:
        version: 9

    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: Install Dependencies
      run: |
        pnpm install

    - name: Lint Builder
      run: |
        pnpm lint:builder

    - name: Test Builder
      run: |
        pnpm test:builder

    - name: Typecheck Builder
      run: |
        pnpm typecheck:builder
