name: package/builder - Build -> Test

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'

    - name: Test and Build
      run: |
        yarn install

        cd packages/builder

        yarn lint
        yarn test
        yarn build
