name: package/builder - Build -> Test

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - uses: pnpm/action-setup@v2
      with:
        version: 8

    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'pnpm'

    - name: Test and Build
      run: |
        pnpm install

        cd packages/builder

        pnpm lint
        pnpm test
        pnpm build
