name: Builder - Lint & Test & Typecheck

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - "**"

jobs:
  lint-test-typecheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - uses: pnpm/action-setup@v2
      with:
        version: 8

    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'pnpm'

    - name: Install Dependencies
      run: |
        pnpm install

    - name: Lint Builder
      run: |
        pnpm b-lint    

    - name: Test Builder
      run: |
        pnpm b-test

    - name: Typecheck Builder
      run: |
        pnpm b-typecheck
