name: Data client - Lint & Test & Typecheck
on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - "**"
jobs:
  lint-test-typecheck:
    concurrency: ci-data-client-${{ github.head_ref || github.run_id }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install Dependencies
        run: |
          pnpm install

      # TODO
      # - name: Lint Data Layer
      #   run: |
      #     pnpm dl-lint

      - name: Test Data Layer
        run: |
          pnpm dl-test

      # TODO    
      # - name: Typecheck Explorer
      #   run: |
      #     pnpm ge-typecheck
