name: package/graph/round - Build -> Test
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  build-and-deploy:
    concurrency: ci-graph-${{ github.head_ref || github.run_id }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: packages/graph/round/yarn.lock

      - name: Install Dependencies for Round Manager
        run: |
          yarn install
          cd packages/graph/round
          yarn install

      # - name: Setup
      #   run: |
      #     cd packages/graph
      #     yarn add @graphprotocol/graph-cli
      #     # yarn prepare:goerli
      #     # yarn codegen

      # - name: Test
      #   run: |
      #     cd packages/graph
      #     yarn test
